"use strict";
let Name = 'Aryan';
console.log(Name);
let x = 12;
console.log(x);
let bool = false;
console.log(bool);
let anyType = 'hi there';
console.log("type 1 : ", anyType);
anyType = 12;
console.log("type 2 : ", anyType);
anyType = bool;
console.log("type 3 : ", anyType);
